// Generated by Wrangler by running `wrangler types`

interface Env {
	GEMINI_API_KEY: string;
	ANTHROPIC_API_KEY: string;
	OPENAI_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	AUTH_USERNAME: string;
	AUTH_PASSWORD: string;
}
