#:schema node_modules/wrangler/config-schema.json
name = "ai-gradio-js"

main = "./server.ts"
workers_dev = true
compatibility_date = "2024-09-26"

[assets]
directory = "./build/client"

[build]
command = "pnpm run build"

[vars]
OPENAI_API_KEY = "" # Set this in your environment
ANTHROPIC_API_KEY = "" # Set this in your environment
GOOGLE_API_KEY = "" # Set this in your environment
