#:schema node_modules/wrangler/config-schema.json
name = "ai-gradio-js"

main = "./worker.ts"
workers_dev = true
compatibility_date = "2024-11-06"

[assets]
directory = "./build/client"

[build]
command = "pnpm run build"
upload.format = "modules"
